Data

In [2]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import os
import torch
import numpy as np

ModuleNotFoundError: No module named 'matplotlib'

In [4]:
#change current directory up to parent, only run 1 time!
os.chdir("..")

In [5]:
img=mpimg.imread(f'{os.path.abspath(os.curdir)}/data/archive/img/1.jpg')
#imgplot = plt.imshow(img) 
print(img)

[[[143 142 124]
  [143 142 124]
  [143 142 124]
  ...
  [ 38  36  39]
  [ 38  36  39]
  [ 39  34  38]]

 [[143 142 124]
  [143 142 124]
  [143 142 124]
  ...
  [ 37  35  38]
  [ 38  36  39]
  [ 38  33  37]]

 [[143 142 124]
  [143 142 124]
  [143 142 124]
  ...
  [ 36  34  37]
  [ 36  34  37]
  [ 36  34  37]]

 ...

 [[ 12  12  10]
  [ 15  15  13]
  [ 18  18  16]
  ...
  [134 132 109]
  [129 127 104]
  [122 120  97]]

 [[ 13  13  11]
  [ 17  17  15]
  [ 21  21  19]
  ...
  [136 134 111]
  [130 128 105]
  [122 120  97]]

 [[ 14  14  12]
  [ 18  18  16]
  [ 22  22  20]
  ...
  [137 135 112]
  [131 129 106]
  [122 120  97]]]


In [6]:
print(torch.from_numpy(img))

tensor([[[143, 142, 124],
         [143, 142, 124],
         [143, 142, 124],
         ...,
         [ 38,  36,  39],
         [ 38,  36,  39],
         [ 39,  34,  38]],

        [[143, 142, 124],
         [143, 142, 124],
         [143, 142, 124],
         ...,
         [ 37,  35,  38],
         [ 38,  36,  39],
         [ 38,  33,  37]],

        [[143, 142, 124],
         [143, 142, 124],
         [143, 142, 124],
         ...,
         [ 36,  34,  37],
         [ 36,  34,  37],
         [ 36,  34,  37]],

        ...,

        [[ 12,  12,  10],
         [ 15,  15,  13],
         [ 18,  18,  16],
         ...,
         [134, 132, 109],
         [129, 127, 104],
         [122, 120,  97]],

        [[ 13,  13,  11],
         [ 17,  17,  15],
         [ 21,  21,  19],
         ...,
         [136, 134, 111],
         [130, 128, 105],
         [122, 120,  97]],

        [[ 14,  14,  12],
         [ 18,  18,  16],
         [ 22,  22,  20],
         ...,
         [137, 135, 112],
        

In [27]:
path1=f'{os.path.abspath(os.curdir)}/data/carseg_data/clean_data/0.npy'
path2=f'{os.path.abspath(os.curdir)}/data/carseg_data/clean_data/0_a.npy'
test1=np.load(path1)
test2=np.load(path2)

In [1]:
test2.shape
print("hey")

NameError: name 'test2' is not defined